In [1]:
import numpy as np

In [ ]:
# The .npz files must be in the same directory as this notebook.

In [2]:
names = {}
names['cQei'] = 0
names['cQl3i'] = 1
names['cQlMi'] = 2
names['cbW'] = 3
names['cpQ3'] = 4
names['cpQM'] = 5
names['cpt'] = 6
names['cptb'] = 7
names['ctG'] = 8
names['ctW'] = 9
names['ctZ'] = 10
names['ctei'] = 11
names['ctlSi'] = 12
names['ctlTi'] = 13
names['ctli'] = 14
names['ctp'] = 15

WC_to_analyze_1 = ['cpQ3', 'cpQM', 'cpt', 'cptb', 'cQei', 'ctei', 'ctli', 'ctW'] # The first of the two WCs to graph
WC_to_analyze_2 = ['cbW', 'ctG', 'ctp', 'cQl3i', 'cQlMi', 'ctlTi', 'ctlSi', 'ctZ'] # The second of the two WCs to graph

In [29]:
# Automatic damage checking for frozen
damaged = np.full((8),0)
for num in np.arange(8):
    WC1 = WC_to_analyze_1[num]
    WC2 = WC_to_analyze_2[num]
    try:
        loaded = np.load(f'likelihood_{WC1}_{WC2}.npz')
        for key in list(loaded.keys()):
            print (loaded[key])
    except:
        damaged[num] = 1

for num in np.arange(8):
    if (damaged[num]):
        WC1 = WC_to_analyze_1[num]
        WC2 = WC_to_analyze_2[num]
        print (f'likelihood_{WC1}_{WC2}.npz is damaged!')

[  0.       125.79231  125.15245  ...  94.01443   94.739914  95.46903 ]
[ -2.6314316 -19.946667  -19.946667  ... -15.786667  -15.786667
 -15.786667 ]
[-2.6051433 -9.966666  -9.9       ...  9.833333   9.9        9.966666 ]
[ 0.       85.517006 85.08992  ... 81.41043  82.15024  82.89236 ]
[  1.11527  -29.866667 -29.6      ...  49.333332  49.6       49.866665]
[-1.0158056 -2.99      -2.99      ... -2.21      -2.21      -2.21     ]
[ 0.       55.823013 55.359753 ... 48.78571  49.360527 49.936672]
[  1.3234017 -39.883335  -39.65      ...  29.416666   29.65
  29.883333 ]
[ -8.378783 -34.833332 -34.833332 ... -21.833334 -21.833334 -21.833334]
[ 0.       80.61933  80.40747  ... 50.74988  51.077747 51.40944 ]
[ -0.08017647 -39.866665   -39.866665   ... -29.466667   -29.466667
 -29.466667  ]
[ -6.038691 -19.933332 -19.8      ...  19.666666  19.8       19.933332]
[  0.       148.06607  147.50652  ... 119.93772  120.679695 121.421524]
[ -0.3143186 -15.946667  -15.84      ...  15.733334   15.84
  1

In [30]:
# Automatic damage checking for profiled
damaged = np.full((8),0)
for num in np.arange(8):
    WC1 = WC_to_analyze_1[num]
    WC2 = WC_to_analyze_2[num]
    try:
        loaded = np.load(f'likelihood_profiled_{WC1}_{WC2}.npz')
        for key in list(loaded.keys()):
            print (loaded[key])
    except:
        damaged[num] = 1

for num in np.arange(8):
    if (damaged[num]):
        WC1 = WC_to_analyze_1[num]
        WC2 = WC_to_analyze_2[num]
        print (f'likelihood_profiled_{WC1}_{WC2}.npz is damaged!')

[  0.       103.704575 103.07477  ...  77.69011   78.384865  79.08358 ]
[ -1.8158566 -19.946667  -19.946667  ... -15.786667  -15.786667
 -15.786667 ]
[ 3.1827962 -9.966666  -9.9       ...  9.833333   9.9        9.966666 ]
[0.26654717 0.30258703 0.29207742 ... 0.29663348 0.29268584 0.30966642]
[-3.4457572 -3.5088074 -3.5151663 ... -3.9457383 -3.8709967 -3.9866369]
[-0.8029149 17.480116  17.52324   ... 13.921238  13.941639  13.861916 ]
[0.29282084 0.1801394  0.16865234 ... 0.20901985 0.2168232  0.19355884]
[ 0.475775   -0.5471742  -0.54950243 ... -0.22866964 -0.23110102
 -0.2504275 ]
[-6.9763603 -9.304051  -9.384032  ... -7.1374474 -7.092437  -7.0624022]
[-7.4944932e-05  4.6587204e-05  6.1074483e-05 ... -8.4765099e-07
 -3.6998356e-06 -7.5178141e-06]
[ 0.11378095 -2.4897096  -2.4704497  ...  2.3223634   2.34048
  2.3597174 ]
[-0.84903574 -1.6272517  -1.6225238  ... -1.5664386  -1.5698968
 -1.5740892 ]
[-0.08534373  0.31930307  0.32221845 ...  0.24861309  0.2477435
  0.24571346]
[-0.081046

[ -3.4457572  22.668854   22.94207   ... -27.927042  -28.0441
 -28.07623  ]
[-0.8029149  7.5263405  7.686131  ... -8.262258  -8.280357  -8.345164 ]
[3.1827962 1.5889556 1.1548626 ... 5.749495  5.7523513 5.75193  ]
[ 0.29282084  0.9522179   0.95778996 ... -0.18912649 -0.19317693
 -0.18946093]
[ 0.475775   -0.05798391 -0.04955541 ...  1.0241389   1.0267909
  1.0312927 ]
[-6.9763603 28.622515  29.052542  ... 16.214708  16.199156  16.188843 ]
[-7.4944932e-05 -2.1601290e-02 -2.1645758e-02 ... -1.4742456e-02
 -1.4766833e-02 -1.4922330e-02]
[ 0.11378095 -0.43056512 -0.330524   ...  0.21720012  0.2645155
  0.25376216]
[-0.84903574  0.09226759  0.09163649 ... -0.00985346 -0.01023991
 -0.00807549]
[-0.08534373  3.5360532   3.5216773  ... -1.2895361  -1.3139485
 -1.3521404 ]
[-0.0810469  3.7490072  3.7287903 ... -1.2731087 -1.2991617 -1.3406253]
[-1.8158566   2.597448    2.7786577  ...  0.5126107   0.54171765
  0.5487753 ]
[-4.2914805  -0.99886197 -1.0062732  ...  0.2721178   0.27231246
  0.28034

In [6]:
# Check training data .npz files
loaded = np.load('likelihood_data.npz') # 5M data set
for key in list(loaded.keys()):
            print (loaded[key])

[ 0.12585062 -5.8946576   9.871703   ...  2.307745   -0.53587836
 -3.032289  ]
[ 3.7470946  -7.4805665  14.620755   ...  8.171228    6.962343
 -0.70265305]
[ 0.52993304 -6.4999213   8.388563   ...  2.5610917   4.223656
  2.1434786 ]
[ 3.1443787 -5.2683115 -9.660264  ... -2.58731    3.3698776  3.906747 ]
[-1.9256926 -4.152191  -3.0596669 ... -2.4844382  2.7288363 -6.755455 ]
[ 8.2205946e-04 -1.2930539e+01 -1.2228927e+01 ...  1.5447581e+01
  2.1020533e+01  1.7434576e+01]
[ -2.590418  19.484354 -32.820053 ... -13.430386  -9.511533 -14.05074 ]
[  0.0632016  14.226492  -34.87008   ...  -2.16115    -8.596648
 -10.632853 ]
[-0.8707601 -2.8808258 -2.9910614 ... -1.354293  -0.357477   0.8399258]
[ 0.45479923 -0.93756247 -1.6039073  ... -2.8773391   2.6306953
 -2.2910068 ]
[ 0.5482334  1.9326702 -2.5298085 ...  2.404292   2.9841018 -2.5852675]
[  0.31173447  13.996884   -16.81361    ...   3.250758     3.183815
  -3.6886425 ]
[ 3.4751149e-05  1.9779690e+01 -1.6801342e+01 ...  3.9076126e+00
  5.95

In [7]:
loaded = np.load('likelihood_data_processed.npz') # 7M data set, processed
for key in list(loaded.keys()):
            print (loaded[key])

[ 0.12585062 -5.8946576   9.871703   ... -0.15579912 -1.1698579
  1.7192854 ]
[ 3.7470946 -7.4805665 14.620755  ...  6.671828  -4.909288   6.653574 ]
[ 0.52993304 -6.4999213   8.388563   ... -1.2988718   0.8602367
 -2.0396159 ]
[ 3.1443787  -5.2683115  -9.660264   ... -1.7467389  -1.5217757
  0.22874588]
[-1.9256926  -4.152191   -3.0596669  ... -5.860529   -1.832111
 -0.40180194]
[ 8.2205946e-04 -1.2930539e+01 -1.2228927e+01 ...  7.9303808e+00
 -2.6258283e+00  9.1085539e+00]
[ -2.590418  19.484354 -32.820053 ...   4.815743 -16.141338   2.707774]
[ 6.3201599e-02  1.4226492e+01 -3.4870079e+01 ... -3.0830860e-02
 -8.8156242e+00 -8.2309647e+00]
[-0.8707601 -2.8808258 -2.9910614 ...  0.5704374 -1.0621672 -0.6949917]
[ 0.45479923 -0.93756247 -1.6039073  ... -0.22071695 -0.51243186
 -1.6449069 ]
[ 0.5482334   1.9326702  -2.5298085  ... -0.16759619 -0.49818116
 -1.7820951 ]
[  0.31173447  13.996884   -16.81361    ...   0.60025424  -1.2860652
   1.8593248 ]
[ 3.4751149e-05  1.9779690e+01 -1.680

In [8]:
loaded = np.load('likelihood_data_50M.npz') # 50M data set
for key in list(loaded.keys()):
            print (loaded[key])

[ 0.12585062  3.0678308  -3.9142978  ...  2.965634    2.4069002
 -3.9764376 ]
[ 3.7470946 -5.0134444 11.974223  ...  4.4416876 -8.754349  -1.1565481]
[  0.52993304 -12.566583   -16.111216   ...  -3.9670331   -3.7316723
  -0.31226352]
[ 3.1443787 -2.5970929  3.4265616 ... -2.4082403 -4.4092145  0.832499 ]
[-1.9256926 -9.277068  -9.391372  ... -3.6178215 -5.4617977 -3.3040535]
[ 8.2205946e-04 -1.4406698e+01 -1.9373232e+01 ...  5.8305140e+00
  9.5222225e+00  1.6372393e+01]
[ -2.590418  -18.822891    2.6502995 ...  -3.7270503 -13.593202
 -18.254055 ]
[  0.0632016 -26.47455   -38.200863  ...  -1.069594   -5.2867
   9.182019 ]
[-0.8707601  -1.9189672   0.20338069 ...  0.8224547   1.0043763
 -0.13002044]
[ 0.45479923  0.6927238  -2.9850905  ... -3.0068362  -0.8961742
 -2.024776  ]
[ 0.5482334 -5.3289537  3.0993    ... -1.0135453 -1.5970455 -2.4780192]
[ 0.31173447  6.976804   16.403065   ... -3.2106297   2.1813657
 -1.3260571 ]
[ 3.4751149e-05  1.2929980e+01 -1.9562880e+01 ... -5.2030292e+00


In [9]:
loaded = np.load('likelihood_data_50M_new.npz') # 50M data set new
for key in list(loaded.keys()):
            print (loaded[key])

[ 0.12585062  8.117036   13.045929   ... -1.0686888   1.0725508
 -2.0933108 ]
[ 3.7470946   0.3501237  -0.05396932 ... -7.085147   -4.765337
  2.317638  ]
[  0.52993304  13.33921    -16.415499   ...  -2.3081536    1.1173044
   2.7549825 ]
[ 3.1443787  2.9760652  3.3101676 ... -4.454903   1.5967731 -3.509097 ]
[-1.9256926  -5.90548     1.1917344  ...  0.73030543 -5.5516963
 -2.5096104 ]
[8.2205946e-04 2.1858322e+01 4.8412834e+01 ... 7.2144504e+00 3.0314097e+00
 8.5237503e+00]
[-2.590418   5.0527625 11.908319  ...  7.671472  -1.0804657 -1.7781389]
[ 0.0632016  3.893852  38.459183  ...  4.615793   5.0043135 -9.069553 ]
[-0.8707601   0.12607276  2.8804438  ... -0.64174986 -1.1170424
 -0.6936506 ]
[ 0.45479923  3.9299786   4.4301453  ... -1.7698196  -2.0642295
  0.1869397 ]
[ 0.5482334  4.4653897  1.8086045 ... -1.1149765 -1.0483768 -1.6031648]
[ 0.31173447  4.877244    9.011825   ... -1.5795864   2.1816146
 -2.4627352 ]
[ 3.4751149e-05  1.8434841e+01  1.8404690e+01 ... -2.2760198e+00
  1.2

In [10]:
loaded = np.load('likelihood_data_no_delta.npz') # no delta data set (50M)
for key in list(loaded.keys()):
            print (loaded[key])

[ 8.117036  13.045929   5.4866066 ...  2.1572876  0.8710793 -1.0231472]
[  0.3501237   -0.05396932 -17.703093   ...   3.8261697   -0.6734503
  -5.8543963 ]
[ 13.33921    -16.415499    16.364672   ...  -1.8526044   -0.43879473
  -0.5338632 ]
[ 2.9760652  3.3101676 -6.519772  ...  4.2646117  2.9622123  4.8450947]
[-5.90548    1.1917344  2.0710423 ... -5.154044  -5.02609   -3.7038734]
[21.858322  48.412834  12.287061  ...  7.462452  -0.6358355 -6.1091995]
[  5.0527625  11.908319   -1.884871  ... -14.56672   -14.935931
  12.20822  ]
[ 3.893852  38.459183  -1.0883414 ...  1.803153  -1.2297375  8.226964 ]
[ 0.12607276  2.8804438   2.0463505  ... -1.0100721  -0.9014386
 -0.04417134]
[ 3.9299786   4.4301453  -0.81444657 ... -2.1632617   1.5303143
  0.42612177]
[ 4.4653897  1.8086045 -2.572848  ... -1.0416182 -2.3250728 -1.640824 ]
[ 4.877244   9.011825  19.862703  ...  2.6881514  4.668057  -3.0439203]
[18.434841   18.40469     3.1104784  ...  1.4558414   0.79292315
 -1.3926891 ]
[-2.9326854   